# Do not modify this file!	It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.	Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	fileSystems = {
		"/" = {
			device = "/dev/disk/by-uuid/ec22bdfa-ed30-475a-925d-fe5be0b9b04f";
			fsType = "ext4";
		};

		"/F" = {
			device = "/dev/disk/by-uuid/F8BA6370BA632A78";
			fsType = "ntfs-3g";
			options = [ "rw" "uid=1000" ];
		};

		"/K" = {
			device = "/dev/disk/by-uuid/0C5230525230432E";
			fsType = "ntfs-3g";
			options = [ "rw" "uid=1000" ];
		};

		"/boot" = {
			device = "/dev/disk/by-uuid/CC5B-A41C";
			fsType = "vfat";
			options = [ "fmask=0077" "dmask=0077" ];
		};
	};




	boot = {
		initrd = {
			availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
			kernelModules = [ ];
			
#			luks.devices."luks-5ea82bfa-7b05-4429-9fe1-f8ff7e862e4b".device = "/dev/disk/by-uuid/5ea82bfa-7b05-4429-9fe1-f8ff7e862e4b";

		};

		kernelModules = [ "kvm-intel" ];
		extraModulePackages = [ ];
		supportedFilesystems = [ "ntfs" ];
	};

	swapDevices = [ {
		device = "/var/lib/swapfile";
		size = 16*1024;
	} ];

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
